flowchart TD
    A[Пациент] -->|Регистрация, запись| B[Система Медикаменте]
    B -->|Результаты анализов, напоминания| A
    C[Лаборатория] -->|Анализы| B
    B -->|Направления| C
    D[Банк] -->|Платежи| B
    B -->|Финансовые отчёты| E[Налоговая]