flowchart TD
    subgraph " "
    A[Пациент] -->|Данные| B[Ресепшен]
    B -->|Запись| C[База пациентов]
    C -->|Доступ| D[Врачи]
    D -->|Диагнозы| C
    D -->|Направления| E[Лаборатория]
    E -->|Результаты| C
    F[Кассир] -->|Платежи| G[1С Бухгалтерия]
    H[Склад] -->|Учёт ТМЦ| I[1С Торговля]
    I -->|Отчёты| G
    G -->|Налоги| J[Налоговая]
    end